import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Space-X App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* --------------------------------- Header --------------------------------- */}
        <header>{/* Logo */}</header>
        {/* ------------------------------ Hero Section ------------------------------ */}
        <section>{/* Search Section */}</section>
        <section>{/* Launches List Section */}</section>
        <section>{/* Pagination Section */}</section>
      </main>
    </>
  );
}
